@startuml general_algorithm
start
:obtain_a_networked_environment_description;
group Networked environment modeling
:determine_green_actions_observations_goals;
:determine_red_actions_observations_goals;
:determine_blue_actions_observations_goals;
:create_networked_environment_model;
:networked_environment_model]
end group
group Red scenario modeling
:determine_a_green_team_behavior;
:determine_a_red_team_behavior;
:red_scenario_model]
end group
repeat
group Blue scenario modeling
:determine_a_blue_team_behavior;
:blue_scenario_model]
end group
:implement_blue_scenario_model_in_simulation;
group Blue scenario evaluation in simulation
:evaluate_in_simulation;
if (cumulative_reward>treshold?) then (Yes)
:add_simulation_validated_blue_scenario;
else (No)
endif
end group
repeat while (Collected N simulation validated\nblue scenarios?)

repeat
:implement_a_validated_blue_scenario_in_emulation;
group Blue scenario evaluation in emulation
:evaluate_in_emulation;
if (success_criteria_observed?) then (Yes)
:add_emulation_validated_blue_scenario;
else (No)
endif
end group
repeat while (All simulation validated\nblue scenario evaluated?)

group Blue team organization analysis
fork
 :characterize_environment;
fork again
 :characterize_green_team;
fork again
 :characterize_red_team;
end fork

repeat
:characterize_organization_in_blue_team_of_an_emulation_validated_blue_scenarios;
:update_relations_for_organization_and_green_team_and_red_team_and_environment;
repeat while (All emulation validated blue scenarios analyzed?)
end group
:relations_for_organization_and_green_team_and_red_team_and_environment]
:save_relations_in_general_blue_team_deployment_model;
stop
@enduml
