@startuml general_algorithm
start
:obtain_a_networked_environment_description;
note right
    Generate (possibly by hand) a sufficiently
    detailed file describing a networked
    environment for each node and how it is
    likely to be attacked and defended
end note
:networked_environment_description]
group Networked environment modeling
    :determine_green_actions_observations_goals;
    note right
        From networked environment description,
        list possible actions, observations and
        goals that regular users are likely to get
    end note
    :green_enriched_networked_environment_description]
    :determine_red_actions_observations_goals;
    note right
        From green enriched networked environment
        description, list possible actions,
        observations and goals that
        cyber-attackers are likely to get
    end note
    :green_and_red_enriched_networked_environment_description]
    :determine_blue_actions_observations_goals;
    note right
        From green and red enriched networked
        environment description, list possible
        actions, observations and goals that
        cyber-defenders are likely to get
    end note
    :green_red_blue_enriched_networked_environment_description]
    :create_networked_environment_model;
    note right
        Optionally getting help from CybMASDE,
        generate a CybMASDE formatted file
        describing the networked environment
        including nodes allowing green, red,
        and blue agents to get, apply and
        reach their respective observations,
        actions, and goals
    end note
    :networked_environment_model]
    end group
    group Red scenario modeling
        :determine_a_green_team_behavior;
        note right
            Optionally getting help from CybMASDE,
            define a behavior for each green agent
            in networked environment model, so
            green team can reach its goal comparing
            described regular activities
        end note
        :green_scenario_model]
        :determine_a_red_team_behavior;
        note right
            Optionally getting help from CybMASDE,
            define a behavior for each red agent
            in green scenario model, so red team
            can reach its goal comparing green
            scenario model or relying on known on
            cyber-attacks or or AI trained models

        end note
        :red_scenario_model]
        end group
        repeat
            group Blue scenario modeling
                :determine_a_blue_team_behavior;
                note right
                    Optionally getting help from CybMASDE,
                    define a behavior for each blue agent
                    in red scenario model, so blue team
                    can reach its goal comparing red
                    scenario model or relying known on
                    cyber-defense strategies or AI
                    trained models
                end note
                :blue_scenario_model]
                end group
                :implement_blue_scenario_model_in_simulation;
                note right
                    Use CybMASDE simulator to implement
                    the networked environment, the green,
                    red, and blue teams of a blue
                    scenario model
                end note
                group Blue scenario evaluation in simulation
                    :evaluate_in_simulation;
                    note right
                        Launch the simulation over one episode
                        to compute the cumulative reward
                    end note
                    :cumulative_reward]
                    if (cumulative_reward>treshold?) then (Yes)
                        note right
                            Treshold allows filtering
                            blue scenarios according
                            to the blue agents
                            performances
                        end note
                        :add_simulation_validated_blue_scenario;
                        note left
                            Add validated blue scenarios
                            in the collection
                        end note
                        :simulation_validated_blue_scenarios]
                    else (No)
                    endif
                    end group
                repeat while (Collected N simulation validated\nblue scenarios?)

                repeat
                    :implement_a_validated_blue_scenario_in_emulation;
                    note left
                        Use CybMASDE emulator to implement
                        the networked environment, the green,
                        red, and blue teams of a blue
                        scenario model.
                        It deploys agents as python scripts
                        and adapts them to activate on signal.
                        Expected results for red and blue
                        teams are defined.
                    end note
                    group Blue scenario evaluation in emulation
                        :evaluate_in_emulation;
                        note right
                            Emmit activate signals so green, red and
                            blue teams start interacting together
                        end note
                        if (success_signal_observed?) then (Yes)
                            note right
                                Success signal is raised
                                when the CybMASDE emulator
                                eventually observe blue
                                agent expected results
                            end note
                            :add_emulation_validated_blue_scenario;
                            note left
                                Add validated blue scenarios
                                in the collection
                            end note
                        else (No)
                        endif
                        end group
                    repeat while (All simulation validated\nblue scenario evaluated?)

                    group Blue team organization analysis
                        fork
                            :characterize_environment;
                            note left
                                Compute a one shot
                                encoded simplified
                                characterization of
                                environment
                            end note
                            :environment_characterization]
                        fork again
                            :characterize_green_team;
                            note left
                                Compute a one shot
                                encoded simplified
                                characterization
                                of a green team
                                behavior
                            end note
                            :green_team_characterization]
                        fork again
                            :characterize_red_team;
                            note right
                                Compute a one shot
                                encoded simplified
                                characterization
                                of a red team
                                behavior
                            end note
                            :red_team_characterization]
                        end fork

                        repeat
                            :characterize_organization_in_blue_team_of_an_emulation_validated_blue_scenarios;
                            note left
                                Use the CybMASDE analysis assist
                                to analyze by hand or automatically
                                the organization among blue agents
                            end note
                            :blue_team_organization_characterization]
                            :update_relations_for_organization_and_green_team_and_red_team_and_environment;
                            note left
                                Save relations between considered
                                blue scenario characterized components
                                (i.e. the environment, red team, green
                                team, and blue team organization
                                characterizations)
                            end note
                            :relations_for_organization_and_green_team_and_red_team_and_environment]
                        repeat while (All emulation validated blue scenarios analyzed?)
                        end group
                        stop
                        @enduml
